package com.romaqui.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "asistencia")
public class Asistencia implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idcontrato")
    private Contrato contrato;
    
    @Column(name = "idturno", nullable = false)
    private int idturno;
    
    @Column(name = "idttipoasistencia", nullable = false)
    private int idttipoasistencia;
    
    @Column(name = "tardanza", nullable = false)
    private int tardanza;
    
    @Column(name = "fecha", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fecha;
    
    @Column(name = "horaentrada", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date horaentrada;
    
    @Column(name = "horasalida", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    private Date horasalida;
    
    @Column(name = "rhoraentrada", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date rhoraentrada;
    
    @Column(name = "rhorasalida", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    private Date rhorasalida;

    public Asistencia() {
    }

    public Asistencia(int id, Contrato contrato, Date fecha, Date horaentrada, Date horasalida, Date rhoraentrada) {
        this.id = id;
        this.contrato = contrato;
        this.fecha = fecha;
        this.horaentrada = horaentrada;
        this.horasalida = horasalida;
        this.rhoraentrada = rhoraentrada;
    }

    public Asistencia(int id, Contrato contrato, int idturno, int idttipoasistencia, int tardanza, Date fecha, Date horaentrada, Date horasalida, Date rhoraentrada, Date rhorasalida) {
        this.id = id;
        this.contrato = contrato;
        this.idturno = idturno;
        this.idttipoasistencia = idttipoasistencia;
        this.tardanza = tardanza;
        this.fecha = fecha;
        this.horaentrada = horaentrada;
        this.horasalida = horasalida;
        this.rhoraentrada = rhoraentrada;
        this.rhorasalida = rhorasalida;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public int getIdturno() {
        return idturno;
    }

    public void setIdturno(int idturno) {
        this.idturno = idturno;
    }

    public int getIdttipoasistencia() {
        return idttipoasistencia;
    }

    public void setIdttipoasistencia(int idttipoasistencia) {
        this.idttipoasistencia = idttipoasistencia;
    }

    public int getTardanza() {
        return tardanza;
    }

    public void setTardanza(int tardanza) {
        this.tardanza = tardanza;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getHoraentrada() {
        return horaentrada;
    }

    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }

    public Date getHorasalida() {
        return horasalida;
    }

    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    public Date getRhoraentrada() {
        return rhoraentrada;
    }

    public void setRhoraentrada(Date rhoraentrada) {
        this.rhoraentrada = rhoraentrada;
    }

    public Date getRhorasalida() {
        return rhorasalida;
    }

    public void setRhorasalida(Date rhorasalida) {
        this.rhorasalida = rhorasalida;
    }

}
