package com.romaqui.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "inventario")
public class Inventario implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idandamio")
    private Andamio andamio;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idproducto")
    private Producto producto;
    
    @Column(name = "cantidad", nullable = false, precision = 11, scale = 1)
    private double cantidad;
    
    @Column(name = "preciomenmin", nullable = false, precision = 8, scale = 2)
    private double preciomenmin;
    
    @Column(name = "preciomenmax", nullable = false, precision = 8, scale = 2)
    private double preciomenmax;
    
    @Column(name = "preciomaymin", nullable = false, precision = 8, scale = 2)
    private double preciomaymin;
    
    @Column(name = "preciomaymax", nullable = false, precision = 8, scale = 2)
    private double preciomaymax;
    
    @Column(name = "estado", nullable = false)
    private boolean estado;
    
    @Column(name = "idusuariocrea", nullable = false)
    private int idusuariocrea;
    
    @Column(name = "fechusuariocrea", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fechusuariocrea;
    
    @Column(name = "idusuariomod", nullable = true)
    private Integer idusuariomod;
    
    @Column(name = "fechusuariomod", nullable = true)
    @Temporal(TemporalType.DATE)
    private Date fechusuariomod;

    public Inventario() {
    }

    public Inventario(int id, Andamio andamio, Producto producto, double cantidad, double preciomenmin, double preciomenmax, double preciomaymin, double preciomaymax, boolean estado, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.andamio = andamio;
        this.producto = producto;
        this.cantidad = cantidad;
        this.preciomenmin = preciomenmin;
        this.preciomenmax = preciomenmax;
        this.preciomaymin = preciomaymin;
        this.preciomaymax = preciomaymax;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Inventario(int id, Andamio andamio, Producto producto, double cantidad, double preciomenmin, double preciomenmax, double preciomaymin, double preciomaymax, boolean estado, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.andamio = andamio;
        this.producto = producto;
        this.cantidad = cantidad;
        this.preciomenmin = preciomenmin;
        this.preciomenmax = preciomenmax;
        this.preciomaymin = preciomaymin;
        this.preciomaymax = preciomaymax;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Andamio getAndamio() {
        return this.andamio;
    }

    public void setAndamio(Andamio andamio) {
        this.andamio = andamio;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getPreciomenmin() {
        return preciomenmin;
    }

    public void setPreciomenmin(double preciomenmin) {
        this.preciomenmin = preciomenmin;
    }

    public double getPreciomenmax() {
        return preciomenmax;
    }

    public void setPreciomenmax(double preciomenmax) {
        this.preciomenmax = preciomenmax;
    }

    public double getPreciomaymin() {
        return preciomaymin;
    }

    public void setPreciomaymin(double preciomaymin) {
        this.preciomaymin = preciomaymin;
    }

    public double getPreciomaymax() {
        return preciomaymax;
    }

    public void setPreciomaymax(double preciomaymax) {
        this.preciomaymax = preciomaymax;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
