package com.romaqui.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Inventarioiniciomes generated by hbm2java
 */
@Entity
@Table(name = "inventarioiniciomes")
public class Inventarioiniciomes implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idproducto")
    private Producto producto;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idagencia")
    private Agencia agencia;
    
    @Column(name = "cantidad", nullable = false, precision = 11, scale = 1)
    private double cantidad;
    
    @Column(name = "precio", nullable = false, precision = 8, scale = 2)
    private double precio;
    
    @Column(name = "fecha", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fecha;
    
    @Column(name = "anio", nullable = false)
    private int anio;
    
    @Column(name = "mes", nullable = false)
    private int mes;
    
    @Column(name = "dia", nullable = false)
    private int dia;

    public Inventarioiniciomes() {
    }

    public Inventarioiniciomes(Producto producto, Agencia agencia, double cantidad, double precio, Date fecha, int anio, int mes, int dia) {
        this.producto = producto;
        this.agencia = agencia;
        this.cantidad = cantidad;
        this.precio = precio;
        this.fecha = fecha;
        this.anio = anio;
        this.mes = mes;
        this.dia = dia;
    }

    public Inventarioiniciomes(int id, Producto producto, Agencia agencia, double cantidad, double precio, Date fecha, int anio, int mes, int dia) {
        this.id = id;
        this.producto = producto;
        this.agencia = agencia;
        this.cantidad = cantidad;
        this.precio = precio;
        this.fecha = fecha;
        this.anio = anio;
        this.mes = mes;
        this.dia = dia;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Agencia getAgencia() {
        return agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getPrecio() {
        return this.precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getAnio() {
        return this.anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    public int getMes() {
        return this.mes;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }

    public int getDia() {
        return this.dia;
    }

    public void setDia(int dia) {
        this.dia = dia;
    }

}
