package com.romaqui.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name = "movimiento")
public class Movimiento implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idagencia")
    private Agencia agencia;

    @Column(name = "idtestadomovimiento", nullable = false)
    private int idtestadomovimiento;

    @Column(name = "idttipomovimiento", nullable = false)
    private int idttipomovimiento;

    @Column(name = "codigo", nullable = false, length = 25)
    private String codigo;

    @Column(name = "montototal", nullable = false, precision = 10, scale = 2)
    private double montototal;

    @Column(name = "urldocumento", nullable = true, length = 300)
    private String urldocumento;

    @Column(name = "observacion", nullable = true, length = 500)
    private String observacion;

    @Column(name = "idusuariocrea", nullable = false)
    private int idusuariocrea;

    @Column(name = "fechusuariocrea", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fechusuariocrea;

    @Column(name = "idusuariomod", nullable = true)
    private Integer idusuariomod;

    @Column(name = "fechusuariomod", nullable = true)
    @Temporal(TemporalType.DATE)
    private Date fechusuariomod;

    public Movimiento() {
    }

    public Movimiento(int id, Agencia agencia, int idtestadomovimiento, int idttipomovimiento, String codigo, double montototal, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.agencia = agencia;
        this.idtestadomovimiento = idtestadomovimiento;
        this.idttipomovimiento = idttipomovimiento;
        this.codigo = codigo;
        this.montototal = montototal;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Movimiento(int id, Agencia agencia, int idtestadomovimiento, int idttipomovimiento, String codigo, double montototal, String urldocumento, String observacion, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.agencia = agencia;
        this.idtestadomovimiento = idtestadomovimiento;
        this.idttipomovimiento = idttipomovimiento;
        this.codigo = codigo;
        this.montototal = montototal;
        this.urldocumento = urldocumento;
        this.observacion = observacion;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public int getIdtestadomovimiento() {
        return this.idtestadomovimiento;
    }

    public void setIdtestadomovimiento(int idtestadomovimiento) {
        this.idtestadomovimiento = idtestadomovimiento;
    }

    public int getIdttipomovimiento() {
        return this.idttipomovimiento;
    }

    public void setIdttipomovimiento(int idttipomovimiento) {
        this.idttipomovimiento = idttipomovimiento;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public double getMontototal() {
        return this.montototal;
    }

    public void setMontototal(double montototal) {
        this.montototal = montototal;
    }

    public String getUrldocumento() {
        return this.urldocumento;
    }

    public void setUrldocumento(String urldocumento) {
        this.urldocumento = urldocumento;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
