package com.romaqui.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso")
public class Permiso implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idcontrato")
    private Contrato contrato;
    
    @Column(name = "idttipopermiso", nullable = false)
    private int idttipopermiso;
    
    @Column(name = "fecha", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fecha;
    
    @Column(name = "horasalida", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date horasalida;
    
    @Column(name = "horaretorno", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    private Date horaretorno;
    
    @Column(name = "autorizja", nullable = false)
    private int autorizja;
    
    @Column(name = "autorizjp", nullable = false)
    private int autorizjp;
    
    @Column(name = "destino", nullable = true, length = 250)
    private String destino;
    
    @Column(name = "descripcion", nullable = true, length = 250)
    private String descripcion;

    public Permiso() {
    }

    public Permiso(int id, Contrato contrato, int idttipopermiso, Date fecha, Date horasalida, Date horaretorno, int autorizja, int autorizjp, String destino, String descripcion) {
        this.id = id;
        this.contrato = contrato;
        this.idttipopermiso = idttipopermiso;
        this.fecha = fecha;
        this.horasalida = horasalida;
        this.horaretorno = horaretorno;
        this.autorizja = autorizja;
        this.autorizjp = autorizjp;
        this.destino = destino;
        this.descripcion = descripcion;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public int getIdttipopermiso() {
        return idttipopermiso;
    }

    public void setIdttipopermiso(int idttipopermiso) {
        this.idttipopermiso = idttipopermiso;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getHorasalida() {
        return horasalida;
    }

    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    public Date getHoraretorno() {
        return horaretorno;
    }

    public void setHoraretorno(Date horaretorno) {
        this.horaretorno = horaretorno;
    }

    public int getAutorizja() {
        return autorizja;
    }

    public void setAutorizja(int autorizja) {
        this.autorizja = autorizja;
    }

    public int getAutorizjp() {
        return autorizjp;
    }

    public void setAutorizjp(int autorizjp) {
        this.autorizjp = autorizjp;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
