package com.romaqui.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Rolacceso generated by hbm2java
 */
@Entity
@Table(name = "rolacceso")
public class Rolacceso implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idmoduloacceso")
    private Moduloacceso moduloacceso;

    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;

    @Column(name = "codigo", nullable = false, length = 10)
    private String codigo;

    @Column(name = "ruta", nullable = false, length = 100)
    private String ruta;

    @Column(name = "icono", nullable = false, length = 25)
    private String icono;

    @Column(name = "estado", nullable = false)
    private boolean estado;

    @Transient
    private List funcionaccesos;

    public Rolacceso() {
    }

    public Rolacceso(int id, Moduloacceso moduloacceso, String nombre, String codigo, String ruta, String icono, boolean estado) {
        this.id = id;
        this.moduloacceso = moduloacceso;
        this.nombre = nombre;
        this.codigo = codigo;
        this.ruta = ruta;
        this.icono = icono;
        this.estado = estado;
    }

    public Rolacceso(int id, Moduloacceso moduloacceso, String nombre, String codigo, String ruta, String icono, boolean estado, List funcionaccesos) {
        this.id = id;
        this.moduloacceso = moduloacceso;
        this.nombre = nombre;
        this.codigo = codigo;
        this.ruta = ruta;
        this.icono = icono;
        this.estado = estado;
        this.funcionaccesos = funcionaccesos;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Moduloacceso getModuloacceso() {
        return this.moduloacceso;
    }

    public void setModuloacceso(Moduloacceso moduloacceso) {
        this.moduloacceso = moduloacceso;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getRuta() {
        return this.ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public String getIcono() {
        return this.icono;
    }

    public void setIcono(String icono) {
        this.icono = icono;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public List getFuncionaccesos() {
        return this.funcionaccesos;
    }

    public void setFuncionaccesos(List funcionaccesos) {
        this.funcionaccesos = funcionaccesos;
    }

}
