package com.romaqui.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "transaccion")
public class Transaccion implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(optional = true, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idcajero")
    private Cajero cajero;
    
    @Column(name = "idttipotransaccion", nullable = false)
    private int idttipotransaccion;
    
    @Column(name = "idttipocomprobante", nullable = false)
    private int idttipocomprobante;
    
    @Column(name = "monto", nullable = false, precision = 10)
    private double monto;
    
    @Column(name = "fecha", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fecha;
    
    @Column(name = "nrocomprobante", nullable = true, length = 10)
    private String nrocomprobante;
    
    @Column(name = "srecomprobante", nullable = true, length = 10)
    private String srecomprobante;
    
    @Column(name = "idusuariocrea", nullable = false)
    private int idusuariocrea;
    
    @Column(name = "fechusuariocrea", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date fechusuariocrea;
    
    @Column(name = "idusuariomod", nullable = true)
    private Integer idusuariomod;
    
    @Column(name = "fechusuariomod", nullable = true)
    @Temporal(TemporalType.DATE)
    private Date fechusuariomod;

    public Transaccion() {
    }

    public Transaccion(int idttipotransaccion, int idttipocomprobante, double monto, Date fecha, int idusuariocrea, Date fechusuariocrea) {
        this.idttipotransaccion = idttipotransaccion;
        this.idttipocomprobante = idttipocomprobante;
        this.monto = monto;
        this.fecha = fecha;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Transaccion(int id, Cajero cajero, int idttipotransaccion, int idttipocomprobante, int monto, Date fecha, String codtransaccion, String nrocomprobante, String srecomprobante, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.cajero = cajero;
        this.idttipotransaccion = idttipotransaccion;
        this.idttipocomprobante = idttipocomprobante;
        this.monto = monto;
        this.fecha = fecha;
        this.nrocomprobante = nrocomprobante;
        this.srecomprobante = srecomprobante;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Cajero getCajero() {
        return this.cajero;
    }

    public void setCajero(Cajero cajero) {
        this.cajero = cajero;
    }

    public int getIdttipotransaccion() {
        return this.idttipotransaccion;
    }

    public void setIdttipotransaccion(int idttipotransaccion) {
        this.idttipotransaccion = idttipotransaccion;
    }

    public int getIdttipocomprobante() {
        return this.idttipocomprobante;
    }

    public void setIdttipocomprobante(int idttipocomprobante) {
        this.idttipocomprobante = idttipocomprobante;
    }

    public double getMonto() {
        return this.monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNrocomprobante() {
        return this.nrocomprobante;
    }

    public void setNrocomprobante(String nrocomprobante) {
        this.nrocomprobante = nrocomprobante;
    }

    public String getSrecomprobante() {
        return this.srecomprobante;
    }

    public void setSrecomprobante(String srecomprobante) {
        this.srecomprobante = srecomprobante;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
