package com.romaqui.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Turno generated by hbm2java
 */
@Entity
@Table(name = "turno")
public class Turno implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @Fetch(FetchMode.SELECT)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "idcontrato")
    private Contrato contrato;
    
    @Column(name = "idttipoturno", nullable = false)
    private int idttipoturno;
    
    @Column(name = "horaentrada", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date horaentrada;
    
    @Column(name = "horasalida", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date horasalida;
    
    @Column(name = "dia", nullable = false)
    private int dia;

    public Turno() {
    }

    public Turno(int id, Contrato contrato, int idttipoturno, Date horaentrada, Date horasalida, int dia) {
        this.id = id;
        this.contrato = contrato;
        this.idttipoturno = idttipoturno;
        this.horaentrada = horaentrada;
        this.horasalida = horasalida;
        this.dia = dia;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return this.contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public int getIdttipoturno() {
        return this.idttipoturno;
    }

    public void setIdttipoturno(int idttipoturno) {
        this.idttipoturno = idttipoturno;
    }

    public Date getHoraentrada() {
        return this.horaentrada;
    }

    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }

    public Date getHorasalida() {
        return this.horasalida;
    }

    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    public int getDia() {
        return dia;
    }

    public void setDia(int dia) {
        this.dia = dia;
    }

}
